apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emp-portal 
  template:
    metadata:
      labels:
        app: emp-portal
    spec:
      containers:
      - name: emp-portal
        image: docker.io/service/emp-portal
        imagePullPolicy: Never
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: emp-portal #emp-portal microservicename
spec:
  ports:
  - port: 8080 #port accessible inside cluster
    protocol: TCP
    targetPort: 80 #port accessible outside cluster
    nodePort: 3000
  selector:
    app: emp-portal #selector checks the name app in deployment name as emp-portal 
  type: NodePort